In [1]:
import torch

x = torch.Tensor ([10, 3])
y = torch.Tensor ([8, 5])

print (x*y)

tensor([80., 15.])


In [2]:
x = torch.zeros([8, 3])
print (x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
print (x.shape)

torch.Size([8, 3])


In [4]:
y = torch.rand([3, 6])
print (y)

tensor([[0.3495, 0.8190, 0.9127, 0.9356, 0.1675, 0.1176],
        [0.5807, 0.7295, 0.7556, 0.8373, 0.1649, 0.7466],
        [0.3269, 0.2139, 0.5560, 0.3119, 0.1610, 0.6339]])


In [6]:
y.view ([9,2])

tensor([[0.3495, 0.8190],
        [0.9127, 0.9356],
        [0.1675, 0.1176],
        [0.5807, 0.7295],
        [0.7556, 0.8373],
        [0.1649, 0.7466],
        [0.3269, 0.2139],
        [0.5560, 0.3119],
        [0.1610, 0.6339]])

In [7]:
y

tensor([[0.3495, 0.8190, 0.9127, 0.9356, 0.1675, 0.1176],
        [0.5807, 0.7295, 0.7556, 0.8373, 0.1649, 0.7466],
        [0.3269, 0.2139, 0.5560, 0.3119, 0.1610, 0.6339]])

In [8]:
y = y.view ([9,2])

In [9]:
y

tensor([[0.3495, 0.8190],
        [0.9127, 0.9356],
        [0.1675, 0.1176],
        [0.5807, 0.7295],
        [0.7556, 0.8373],
        [0.1649, 0.7466],
        [0.3269, 0.2139],
        [0.5560, 0.3119],
        [0.1610, 0.6339]])